### ISSUE TITLE
can this project be compiled to a  .dll ?

### ISSUE THREAD

**Issue by LebronJames0423** [pntt3011/mediapipe_face_iris_cpp#6]
This project is really good, but can you tell me how can i use the code in another project? in a dll way or other way? thank you very much

**Comment by pntt3011** [comment]
Thank you for your question.
In case your project is written in c++, you can copy all the .cpp, .h files to your working directory and use the classes provided like normal. 
I just use cmake because it helps linking the libraries (opencv, tflite) easier. Visual studio IDE can do it too ([opencv tutortial](https://www.youtube.com/watch?v=unSce_GPwto)). As long as the necessary libraries are linked when you compile, you can use the .cpp .h everywhere you want. 
If you really need the .dll, i will try to find some ways. Cmake supports building .dll instead of .exe so I think it's not that hard.

**Comment by LebronJames0423** [comment]
it works! thank you!
